name: Build and run all tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get and verify dependencies
      run: go mod download && go mod verify

    - name: Build app to make sure there are zero issues
      run: go build -o app ./cmd

    - name: Run all tests
      run: go test -v ./...
