name: Build, run all tests and deploy Docker image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get and verify dependencies
      run: go mod download && go mod verify

    - name: Build app to make sure there are zero issues
      run: go build -o app ./cmd

    - name: Run all tests
      run: go test -v ./...

    - name: Login to Github registry
      if:  github.ref == 'refs/heads/master'
      uses: actions-hub/docker/login@master
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_REGISTRY_URL: docker.pkg.github.com

    - name: Build latest image
      if: success() &&  github.ref == 'refs/heads/master'
      run: docker build -t docker.pkg.github.com/${{ github.repository }}/server:latest .

    - name: Push to Github Packages :latest
      if: success() && github.ref == 'refs/heads/master'
      uses: actions-hub/docker@master
      with:
        args: push docker.pkg.github.com/${{ github.repository }}/server:latest
